# 💻 Laptop Price Prediction

## 📌 Project Overview

This project focuses on cleaning, preprocessing, and analyzing an uncleaned laptop dataset and developing a machine learning regression model to predict laptop prices based on their specifications.

The dataset contains more than 1,300 laptop product listings with information about brands, laptop types, screen specifications, processors, RAM, storage, GPUs, operating systems, weight, and price.

The main challenge of this project is that the original dataset contains various data quality issues, including missing values, inconsistent formats, mixed data types, and unstructured information. Therefore, a significant part of the project focuses on **data cleaning and feature engineering** before applying machine learning techniques.

The project follows a typical end-to-end data science workflow:

**Data Cleaning → Exploratory Data Analysis → Feature Engineering → Data Preprocessing → Model Training → Model Evaluation**

---

## 🎯 Project Objective

The main objective is to build a machine learning model that can estimate the price of a laptop based on its technical specifications.

More specifically, the project aims to:

- Clean and preprocess the raw dataset
- Identify and handle missing and inconsistent values
- Convert unstructured information into useful numerical features
- Explore relationships between laptop specifications and price
- Perform feature engineering
- Encode categorical variables
- Scale numerical features where appropriate
- Train regression models
- Evaluate model performance using appropriate regression metrics
- Identify the most important factors affecting laptop prices

---

## 📊 Dataset Summary

The dataset contains **1,300+ laptop product listings** and provides information about different laptop models and their technical specifications.

The dataset contains both **categorical** and **numerical** variables.

### Categorical Features

Examples include:

- Brand
- Laptop Type
- Screen Resolution
- CPU
- Storage Type
- GPU
- Operating System

### Numerical Features

Examples include:

- Screen Size
- RAM
- Storage Capacity
- Weight
- Price

The target variable is:

> **Price** — a continuous numerical variable representing the price of the laptop.

---

## 🧹 Data Quality Challenges

The original dataset is intentionally uncleaned and contains several data quality issues that need to be addressed before modeling.

These include:

- Missing values
- Inconsistent formatting
- Mixed data types
- Numerical values stored as strings
- Units included inside numerical columns
- Multiple pieces of information stored in a single column
- Inconsistent categorical values
- Potential outliers

For example, specifications such as CPU, storage, and screen resolution contain multiple pieces of information in a single text field.

Therefore, the preprocessing stage is an important part of this project.

---

## 🔧 Feature Engineering

One of the main goals of this project is to transform the raw laptop specifications into meaningful machine learning features.

Examples of potential feature engineering include:

- Extracting CPU brand and processor family
- Extracting CPU speed
- Converting RAM into numerical values
- Extracting storage capacity
- Separating SSD and HDD storage
- Extracting screen width and height from resolution
- Calculating total pixels
- Creating screen aspect ratio
- Extracting GPU brand
- Converting laptop weight to numerical values
- Encoding operating systems
- Encoding laptop brands and types

These transformations allow the machine learning model to work with structured numerical and categorical information rather than raw text.

---

## 📋 Column Descriptions

| Column | Description |
|---|---|
| **Brand** | The manufacturer of the laptop, such as Apple, HP, Acer, Dell, Asus, Lenovo, or Chuwi. |
| **Type** | The type of laptop, such as Ultrabook, Notebook, Gaming, or 2-in-1 Convertible. |
| **Screen Size** | The diagonal screen size measured in inches. |
| **Screen Resolution** | The display resolution of the laptop. |
| **CPU** | The processor type and speed, such as Intel Core i5 2.3GHz or AMD A9-Series 9420 3GHz. |
| **RAM** | The amount of RAM installed, measured in GB. |
| **Storage Type** | The type of storage device, such as SSD, HDD, or Flash Storage. |
| **Storage Size** | The storage capacity of the laptop. |
| **GPU** | The graphics processing unit and its specifications. |
| **Operating System** | The operating system installed on the laptop, such as Windows, macOS, or Linux. |
| **Weight** | The weight of the laptop measured in kilograms. |
| **Price** | The selling price of the laptop and the target variable for the prediction model. |

---

## 🔍 Exploratory Data Analysis

The exploratory analysis investigates the relationship between laptop specifications and prices.

Some of the questions explored include:

- Which laptop brands have the highest average prices?
- Does RAM have a strong relationship with price?
- How does storage capacity affect price?
- Are SSD laptops more expensive than HDD laptops?
- Does screen resolution influence price?
- How does CPU performance relate to price?
- Does GPU type have a significant effect on price?
- Are there significant price differences between operating systems?
- Which features have the strongest relationship with laptop price?

Visualizations are used to identify trends, distributions, relationships, and potential outliers.

---

## 🤖 Machine Learning

Since **Price** is a continuous numerical target, this project is treated as a **regression problem**.

The project starts with a simple baseline model and then evaluates more advanced approaches.

Potential models include:

- Linear Regression
- Ridge Regression
- Lasso Regression
- Random Forest Regressor
- Gradient Boosting Regressor

The models can then be compared to determine which approach provides the best predictive performance.

---

## 📏 Model Evaluation

The regression models are evaluated using several metrics:

### Mean Absolute Error (MAE)

Measures the average absolute difference between the actual and predicted prices.

\[
MAE = \frac{1}{n}\sum |y_i-\hat{y_i}|
\]

### Root Mean Squared Error (RMSE)

Penalizes larger prediction errors more strongly than MAE.

\[
RMSE = \sqrt{\frac{1}{n}\sum(y_i-\hat{y_i})^2}
\]

### R² Score

Measures how much of the variation in laptop prices is explained by the model.

\[
R^2 = 1-\frac{SS_{res}}{SS_{tot}}
\]

The final model will be evaluated using the test dataset to estimate its performance on previously unseen laptop specifications.

---

## 🛠️ Technologies & Libraries

The project is developed using Python and the following libraries:

- **Python**
- **Pandas** — Data manipulation and cleaning
- **NumPy** — Numerical computing
- **Matplotlib** — Data visualization
- **Seaborn** — Statistical visualization
- **Scikit-learn** — Machine learning and preprocessing
- **Jupyter Notebook** — Development and analysis environment

---

## 🔄 Project Workflow

```text
Raw Dataset
     ↓
Data Inspection
     ↓
Data Cleaning
     ↓
Handling Missing Values
     ↓
Handling Inconsistent Data
     ↓
Feature Engineering
     ↓
Exploratory Data Analysis
     ↓
Encoding Categorical Features
     ↓
Train/Test Split
     ↓
Feature Scaling
     ↓
Model Training
     ↓
Cross-Validation & Hyperparameter Tuning
     ↓
Model Evaluation
     ↓
Final Laptop Price Prediction

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('laptop_cleaned_data.csv')
df.head()

,Company,Typename,Inches,Weight,Screen_resolution,Display_type,Processor_speed,Processor_brand,Processor_type,Ssd_storage,Hdd_storage,Flash_storage,Ram,Os,Price
0,Apple,Ultrabook,13.3,1.37,2560x1600,Quad HD,2.3,Intel,Core i5,128.0,0.0,0.0,8,mac,71378.6832
1,Apple,Ultrabook,13.3,1.34,1440x900,HD,1.8,Intel,Core i5,0.0,0.0,128.0,8,mac,47895.5232
2,HP,Notebook,15.6,1.86,1920x1080,Full HD,2.5,Intel,Core i5 7200U,256.0,0.0,0.0,8,no,30636.0000
3,Apple,Ultrabook,15.4,1.83,2880x1800,Quad HD,2.7,Intel,Core i7,512.0,0.0,0.0,16,mac,135195.3360
4,Apple,Ultrabook,13.3,1.37,2560x1600,Quad HD,3.1,Intel,Core i5,256.0,0.0,0.0,8,mac,96095.8080

In [3]:
df.columns = df.columns.str.lower()

In [5]:
df.sample(5)

,company,typename,inches,weight,screen_resolution,display_type,processor_speed,processor_brand,processor_type,ssd_storage,hdd_storage,flash_storage,ram,os,price
625,HP,Notebook,17.0,2.6,1600x900,HD,3.0,AMD,A9-Series 9420,0.0,1000.0,0.0,8,windows,27753.552
188,HP,Notebook,17.3,2.5,1920x1080,Full HD,1.6,Intel,Core i5 8250U,0.0,1000.0,0.0,8,windows,48697.920
829,Asus,Gaming,15.6,2.1,1920x1080,Full HD,2.8,Intel,Core i7 7700HQ,128.0,1000.0,0.0,16,windows,101178.720
1182,Asus,Notebook,15.6,2.2,1920x1080,Full HD,2.8,Intel,Core i7 7700HQ,128.0,1000.0,0.0,16,windows,93186.720
282,Asus,Gaming,17.3,3.0,1920x1080,Full HD,2.8,Intel,Core i7 7700HQ,0.0,1000.0,0.0,8,windows,63243.360

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1244 entries, 0 to 1243
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   company            1244 non-null   object
 1   typename           1244 non-null   object
 2   inches             1244 non-null   float64
 3   weight             1244 non-null   float64
 4   screen_resolution  1244 non-null   object
 5   display_type       1244 non-null   object
 6   processor_speed    1244 non-null   float64
 7   processor_brand    1244 non-null   object
 8   processor_type     1244 non-null   object
 9   ssd_storage        1244 non-null   float64
 10  hdd_storage        1244 non-null   float64
 11  flash_storage      1244 non-null   float64
 12  ram                1244 non-null   int64
 13  os                 1244 non-null   object
 14  price              1244 non-null   float64
dtypes: float64(7), int64(1), object(7)
memory usage: 145.9+ KB

In [7]:
df.describe()

,inches,weight,processor_speed,ssd_storage,hdd_storage,flash_storage,ram,price
count,1244.000000,1244.000000,1244.000000,1244.000000,1244.000000,1244.000000,1244.000000,1244.000000
mean,15.005949,2.004951,2.303794,184.707395,416.125402,4.540193,8.528135,60606.224427
std,1.455866,0.576723,0.504391,183.809097,520.965077,30.802474,5.586878,37424.636161
min,9.400000,0.000200,0.900000,0.000000,0.000000,0.000000,1.000000,9270.720000
25%,14.000000,1.500000,2.000000,0.000000,0.000000,0.000000,4.000000,32655.445200
50%,15.600000,2.040000,2.500000,256.000000,0.000000,0.000000,8.000000,52693.920000
75%,15.600000,2.310000,2.700000,256.000000,1000.000000,0.000000,8.000000,79813.440000
max,18.400000,4.000000,3.600000,1000.000000,2000.000000,512.000000,64.000000,324954.720000

In [8]:
df['processor_brand'].unique()

array(['Intel', 'AMD', 'Samsung'], dtype=object)

In [33]:
df['processor_brand'].value_counts()

processor_brand
Intel      1183
AMD          60
Samsung       1
Name: count, dtype: int64

```
We can remove Samsung, it has only one value

In [38]:
df[df['processor_brand']=='Samsung']

,company,typename,inches,weight,screen_resolution,display_type,processor_speed,processor_brand,processor_type,ssd_storage,hdd_storage,flash_storage,ram,os,price
1163,Samsung,2 in 1 Convertible,12.3,1.15,2400x1600,Full HD,2.0,Samsung,Cortex A72&A53,0.0,0.0,32.0,4,chrome,35111.52

In [39]:
df = df[df['company'] != 'Samsung'].reset_index(drop=True)

In [40]:
df['processor_speed'].dtype

dtype('float64')

```
We try to use columns which has a reasonable affect and do not overlap others,
to get dummy variables, I choose the display mode instead of resolution and for Cpu, I take the type and the speed 
of a cpu.
the price has a big value so I get the log of it.

In [41]:
X = df.drop(['screen_resolution', 'processor_type', 'price'], axis=1)
y = np.log(df['price'])

In [46]:
X = pd.get_dummies(X, drop_first=True).astype(int)

In [47]:
X.columns

Index(['inches', 'weight', 'processor_speed', 'ssd_storage', 'hdd_storage',
       'flash_storage', 'ram', 'company_Apple', 'company_Asus',
       'company_Chuwi', 'company_Dell', 'company_Fujitsu', 'company_Google',
       'company_HP', 'company_Huawei', 'company_LG', 'company_Lenovo',
       'company_MSI', 'company_Mediacom', 'company_Microsoft', 'company_Razer',
       'company_Toshiba', 'company_Xiaomi', 'typename_Gaming',
       'typename_Notebook', 'typename_Ultrabook', 'typename_Workstation',
       'display_type_Full HD', 'display_type_HD', 'display_type_Quad HD',
       'processor_brand_Intel', 'os_chrome', 'os_linux', 'os_mac', 'os_no',
       'os_windows'],
      dtype='object')

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

### First we apply a simple linear regresion model to predict the price

In [50]:
from sklearn.linear_model import LinearRegression

In [51]:
lr_model = LinearRegression()

In [52]:
lr_model.fit(X_train, y_train)

LinearRegression()

In [53]:
y_pred = lr_model.predict(X_test)

In [54]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [55]:
mean_absolute_error(y_test, y_pred)

0.22998355428036407

In [56]:
np.sqrt(mean_squared_error(y_test, y_pred))

0.32036523341345097

In [57]:
r2_score(y_test, y_pred)

0.7421505779820694

````
Let's change our price to real values

In [84]:
exp_y_test = np.exp(y_test)

In [85]:
exp_y_pred = np.exp(y_pred)

In [89]:
MAE = mean_absolute_error(exp_y_test, exp_y_pred)
MAE

16835.341301830245

In [91]:
mean = df['price'].mean()
mean

60499.08364955467

In [95]:
100 * MAE/mean

27.827431898555986

```
We are about 27% off.
we need to work on our model to predict accurately

In [88]:
np.sqrt(mean_squared_error(exp_y_test,exp_y_pred))

45774.64238875475

```
We put some data to see how our simple LR model predicts.

In [96]:
# as an example, we pick one row from our data and apply the model, so we can compare the price

df.iloc[770]

company                       Dell
typename                  Notebook
inches                        15.6
weight                        1.95
screen_resolution         1366x768
display_type                    HD
processor_speed                2.5
processor_brand              Intel
processor_type       Core i5 7200U
ssd_storage                  128.0
hdd_storage                    0.0
flash_storage                  0.0
ram                              8
os                         windows
price                      43156.8
Name: 770, dtype: object

In [97]:
new_laptop = pd.DataFrame([{
    "company": "Dell",
    "typename": "Notebook",
    "inches": 15.6,
    "weight": 1.95,
    "display_type": "HD",
    "processor_speed": 2.5,
    "processor_brand": "Intel",
    "ssd_storage": 128.0,
    "hdd_storage": 0.0,
    "flash_storage": 0.0,
    "ram": 8,
    "os": "windows"
}])

In [98]:
new_laptop

,company,typename,inches,weight,display_type,processor_speed,processor_brand,ssd_storage,hdd_storage,flash_storage,ram,os
0,Dell,Notebook,15.6,1.95,HD,2.5,Intel,128.0,0.0,0.0,8,windows

In [99]:
new_laptop = pd.get_dummies(new_laptop).astype(int)
new_laptop

,inches,weight,processor_speed,ssd_storage,hdd_storage,flash_storage,ram,company_Dell,typename_Notebook,display_type_HD,processor_brand_Intel,os_windows
0,15,1,2,128,0,0,8,1,1,1,1,1

In [100]:
new_laptop = new_laptop.reindex(
    columns=X_train.columns,   # or X.columns
    fill_value=0
)

In [101]:
new_price = lr_model.predict(new_laptop)
np.exp(new_price)

array([39508.23780624])

````
the difference is 3648 which is a good start but not so accurate

In [104]:
from sklearn.preprocessing import StandardScaler

In [105]:
scaler = StandardScaler()

In [106]:
scaled_x_train = scaler.fit_transform(X_train)
scaled_x_test = scaler.transform(X_test)

In [107]:
from sklearn.linear_model import ElasticNet

In [111]:
el_model = ElasticNet()

In [114]:
param_grids = {'alpha':[0.1,1,10,100], 'l1_ratio':[0,0.1,0.5,0.7,0.95,1]}

In [113]:
from sklearn.model_selection import GridSearchCV

In [116]:
grid_model = GridSearchCV(
    estimator=el_model,
    param_grid=param_grids,
    scoring='neg_mean_squared_error',
    cv=5, verbose=2
)

In [117]:
grid_model.fit(X_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.979e+01, tolerance: 2.645e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.971e+01, tolerance: 2.612e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.029e+01, tolerance: 2.661e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.962e+01, tolerance: 2.476e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.847e+01, tolerance: 2.570e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.247e+01, tolerance: 2.645e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.5s
[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=0; total time=   0.0s

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.293e+01, tolerance: 2.612e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.252e+01, tolerance: 2.661e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.219e+01, tolerance: 2.476e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.141e+01, tolerance: 2.570e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.132e+01, tolerance: 2.645e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.217e+01, tolerance: 2.612e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

[CV] END ................................alpha=1, l1_ratio=0; total time=   0.1s
[CV] END ................................alpha=1, l1_ratio=0; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=0; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.0s

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.158e+01, tolerance: 2.661e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.173e+01, tolerance: 2.476e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.078e+01, tolerance: 2.570e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.751e+01, tolerance: 2.645e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.868e+01, tolerance: 2.612e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.1s
[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.0s

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.820e+01, tolerance: 2.661e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.815e+01, tolerance: 2.476e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.709e+01, tolerance: 2.570e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.1s
[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.1s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.969e+01, tolerance: 3.242e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 10, 100],
                         'l1_ratio': [0, 0.1, 0.5, 0.7, 0.95, 1]},
             scoring='neg_mean_squared_error', verbose=2)

In [118]:
grid_model.best_params_

{'alpha': 0.1, 'l1_ratio': 0}

In [119]:
y_pred = grid_model.predict(X_test)

In [120]:
mean_absolute_error(y_test,y_pred)

0.2635702099327316

In [121]:
np.sqrt(mean_squared_error(y_test, y_pred))

0.3713585659344592

In [128]:
exp_y_pred = np.exp(y_pred)

In [129]:
exp_y_test = np.exp(y_test)

In [130]:
mean_absolute_error(exp_y_test,exp_y_pred)

21951.77772888404

````
Let's apply the model to scaled dataset

In [132]:
grid_model_2 = GridSearchCV(
    estimator=el_model,
    param_grid=param_grids,
    cv=5, scoring='neg_mean_squared_error',
    verbose=2   
)

In [133]:
grid_model_2.fit(scaled_x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.1s
[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=0; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.136e+01, tolerance: 2.645e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.121e+01, tolerance: 2.612e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.217e+01, tolerance: 2.661e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.098e+01, tolerance: 2.476e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.103e+01, tolerance: 2.570e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.433e+01, tolerance: 2.645e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=0; total time=   0.1s
[CV] END ................................alpha=1, l1_ratio=0; total time=   0.1s
[CV] END ................................alpha=1, l1_ratio=0; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=0; total time=   0.0s

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.406e+01, tolerance: 2.612e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.518e+01, tolerance: 2.661e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.310e+01, tolerance: 2.476e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.348e+01, tolerance: 2.570e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.068e+02, tolerance: 2.645e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.058e+02, tolerance: 2.612e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

[CV] END ................................alpha=1, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.0s

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.078e+02, tolerance: 2.661e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.014e+02, tolerance: 2.476e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.041e+02, tolerance: 2.570e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.289e+02, tolerance: 2.645e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.274e+02, tolerance: 2.612e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.297e+02, tolerance: 2.661e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

[CV] END ...............................alpha=10, l1_ratio=0; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.1s
[CV] END ..............................alpha=100, l1_ratio=0; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.209e+02, tolerance: 2.476e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.253e+02, tolerance: 2.570e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.944e+01, tolerance: 3.242e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 10, 100],
                         'l1_ratio': [0, 0.1, 0.5, 0.7, 0.95, 1]},
             scoring='neg_mean_squared_error', verbose=2)

In [134]:
grid_model_2.best_params_

{'alpha': 0.1, 'l1_ratio': 0}

In [135]:
y_preds_2 = grid_model_2.predict(scaled_x_test)

In [136]:
mean_absolute_error(y_test, y_preds_2)

0.22948607109117652

In [137]:
np.sqrt(mean_squared_error(y_test,y_preds_2))

0.31793859772326194

In [139]:
exp_y_pred = np.exp(y_preds_2)

In [140]:
mean_absolute_error(exp_y_test, exp_y_pred)

16400.00325810185

In [141]:
df['price'].mean()

60499.08364955467

```
Let's apply our new model to a random data and compare the new price with the real one

In [207]:
df.iloc[3]

company                   Apple
typename              Ultrabook
inches                     15.4
weight                     1.83
screen_resolution     2880x1800
display_type            Quad HD
processor_speed             2.7
processor_brand           Intel
processor_type          Core i7
ssd_storage               512.0
hdd_storage                 0.0
flash_storage               0.0
ram                          16
os                          mac
price                135195.336
Name: 3, dtype: object

In [213]:
new_laptop = pd.DataFrame([{
    "company": "Apple",
    "typename": "Ultrabook",
    "inches": 15.4,
    "weight": 1.83,
    "display_type": "Quad HD",
    "processor_speed": 2.7,
    "processor_brand": "Intel",
    "ssd_storage": 512.0,
    "hdd_storage": 0.0,
    "flash_storage": 0.0,
    "ram": 16,
    "os": "mac"
}])

In [214]:
new_laptop = pd.get_dummies(new_laptop).astype(int)
new_laptop

,inches,weight,processor_speed,ssd_storage,hdd_storage,flash_storage,ram,company_Apple,typename_Ultrabook,display_type_Quad HD,processor_brand_Intel,os_mac
0,15,1,2,512,0,0,16,1,1,1,1,1

In [216]:
new_laptop = new_laptop.reindex(columns=X_train.columns, fill_value=0)
new_laptop

,inches,weight,processor_speed,ssd_storage,hdd_storage,flash_storage,ram,company_Apple,company_Asus,company_Chuwi,...,typename_Workstation,display_type_Full HD,display_type_HD,display_type_Quad HD,processor_brand_Intel,os_chrome,os_linux,os_mac,os_no,os_windows
0,15,1,2,512,0,0,16,1,0,0,...,0,0,0,1,1,0,0,1,0,0

In [217]:
new_laptop = scaler.transform(new_laptop)
new_laptop

array([[ 0.28414703, -0.9660092 ,  0.4573373 ,  1.86023536, -0.82021671,
        -0.13400658,  1.61469032,  7.79193722, -0.35768329, -0.0340404 ,
        -0.54703576, -0.0340404 , -0.04816831, -0.52915026, -0.04816831,
        -0.04816831, -0.53988871, -0.21742292, -0.05902813, -0.06819943,
        -0.06819943, -0.21151838, -0.0340404 , -0.45093527, -1.16095912,
         2.50209996, -0.1616424 , -1.38525049, -0.59874082,  4.66227864,
         0.22032632, -0.14586499, -0.22885618,  7.79193722, -0.25046083,
        -2.40897273]])

In [218]:
pred_price = grid_model_2.predict(new_laptop)
pred_price

array([11.91472509])

In [219]:
np.exp(pred_price)

array([149451.18397982])

```
It worked good, but we can do better